name: complex
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
        - name: First job
          run: date
  windows:
    runs-on: windows-latest
    steps:
        - name: Second job
          run: date
  macos:
    runs-on: macos-latest
    steps:
        - name: Third job
          run: date
  depends:
    needs: [ubuntu, windows, macos]
    runs-on: macos-latest
    steps:
        - name: Fourth job
          run: date
